### ISSUE TITLE
内网报SSL证书校验错误的问题

### ISSUE THREAD

**Issue by Ca1337** [GhostFrankWu/SUSTech_Tools#15]
内网直接访问会因为 `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]` 异常退出  
推测是tis的证书链配糊了，找不到根证书   
建议修复方案：  

- 本地配置证书
- `verify=False`
- 欢迎提出其他修复方案

**Comment by Acheng0211** [comment]
请问能详细说明下verify=False怎么修改吗，在main源码里没搜索到。另外一个问题是main.exe在输入密码后会自动闪退。感谢

**Comment by Acheng0211** [comment]
<img width="638" alt="image" src="https://github.com/GhostFrankWu/SUSTech_Tools/assets/107821715/89001996-f681-4c6f-9356-45967a8a30c4">

**Comment by Acheng0211** [comment]
> <img alt="image" width="638" src="https://user-images.githubusercontent.com/107821715/246682689-89001996-f681-4c6f-9356-45967a8a30c4.png">

请问增加了verify=false仍然报错可能是什么原因呢？
