### ISSUE TITLE
getinfo函数返回的课程不正确

### ISSUE THREAD

**Issue by rongmengmeng** [GhostFrankWu/SUSTech_Tools#17]
getinfo函数返回的课程不正确，返回的课程并非是我培养计划中的课程，而且两次运行脚本，两次中的getinfo不同。猜测可能是request网址的问题，同时也想问问您是怎么获取到那些url的？

**Comment by rongmengmeng** [comment]
我是南科大-深理工联培的研究生，可能是因为院系特殊的原因，在getinfo函数中的ClassData内出现了大量不在培养计划内的课程(疑似为本科生课程)，比如高数和马原，也就是ClassData内没有一科是在我培养计划内。
![8}{4(~}ESG6}$(H1{)IMAUA](https://github.com/GhostFrankWu/SUSTech_Tools/assets/83903066/c18a4b3a-5e6b-480d-bede-b176f934dcf0)

**Comment by rongmengmeng** [comment]
抱歉，已经弄明白了，是我自己设置错了

**Comment by GhostFrankWu** [comment]
如果有同样问题，请重开issue并提供详情，谢谢

该Issue超过一年无回复，暂时关闭
