### ISSUE TITLE
关于抢课顺序

### ISSUE THREAD

**Issue by Teddy-creator** [GhostFrankWu/SUSTech_Tools#22]
想问问它是按照我输入到课程列表里面的课程顺序抢课的嘛 就比如我同时在Class.txt中输入两门大物课 它是以什么样的顺序来抢的嘛qwq

**Comment by GhostFrankWu** [comment]
目前是近乎随机的顺序，我可以改成按成Class.txt顺序来确定

**Comment by Teddy-creator** [comment]
> 目前是近乎随机的顺序，我可以改成按成Class.txt顺序来确定

那如果这样的话 后面的课程的抢课速度就会慢了嘛

**Comment by GhostFrankWu** [comment]
按照脚本最初的设定是不会慢的，因为发包都是瞬间的事情，相比延迟的几ms，先后顺序完全可以忽略不计。

但是现在TIS限制1s只能有一个请求，所以先后顺序会让后面的课程一定比前面的课程慢。

**Comment by Teddy-creator** [comment]
> 按照脚本最初的设定是不会慢的，因为发包都是瞬间的事情，相比延迟的几ms，先后顺序完全可以忽略不计。
> 
> 但是现在TIS限制1s只能有一个请求，所以先后顺序会让后面的课程一定比前面的课程慢。

所以不管是按近乎随机的顺序还是按Class.txt的顺序，可以理解为只是抢课顺序不同而前后课程的抢课速度都是一样的吗，就是说即使是近乎随机，也是有先后顺序的吗

**Comment by Teddy-creator** [comment]
> 目前是近乎随机的顺序，我可以改成按成Class.txt顺序来确定

麻烦您了，如果可以改成后者的话。

**Comment by GhostFrankWu** [comment]
我记错了，之前就是按录入顺序来的，不过新版本改了策略，一次只选一门课了，如果有更好的策略建议，请新开issue。

感谢提问！
