### ISSUE TITLE
好像学期并未自动更新噢，目前还是显示的第2学期

### ISSUE THREAD

**Issue by Acheng0211** [GhostFrankWu/SUSTech_Tools#5]

**Comment by GhostFrankWu** [comment]
是脚本逻辑上的问题，原因是TIS服务器并没有更新当前所在学年，但是更新了选课学年，所以脚本发送的xq参数不正确

**Comment by Acheng0211** [comment]
使用时暂时检索不到夏季学期的课程，目前还是春季学期的哟

**Comment by GhostFrankWu** [comment]
fixed at #16017b0

**Comment by Acheng0211** [comment]
方便上传下打包版嘛，孩子不会用python，感谢

**Comment by GhostFrankWu** [comment]
打包版已同步更新

**Comment by Acheng0211** [comment]
最后打扰一遍，这好像显示不出来课程名字，我也不清楚有没有成功读入，劳烦了
<img width="736" alt="image" src="https://user-images.githubusercontent.com/107821715/174522189-d53771f6-5122-441e-a89b-3ccb097d269d.png">

**Comment by GhostFrankWu** [comment]
看了下是我改bug出新bug了，我爬，我再改改

**Comment by GhostFrankWu** [comment]
fixed at https://github.com/GhostFrankWu/SUSTech_Tools/releases/tag/v3.1RC1

**Comment by Acheng0211** [comment]
ok了，非常感谢
