### ISSUE TITLE
不能访问CAS, 请检查您的网络连接状态

### ISSUE THREAD

**Issue by Hongstr** [GhostFrankWu/SUSTech_Tools#6]
![image](https://user-images.githubusercontent.com/60701365/174777103-b44e72d2-f810-4f49-9029-1e7755a97c84.png)

二期宿舍有线校园网

**Comment by GhostFrankWu** [comment]
相同网络环境我这边检测正常，据信息中心反馈可能是学校DNS配置错误导致的，请考虑自行配置DNS、更换为热点等方式。
