### ISSUE TITLE
对于研究生课程好像不生效

### ISSUE THREAD

**Issue by fhfhfh999** [GhostFrankWu/SUSTech_Tools#8]
我不擅长脚本，今天测试一下发现该脚本好像读不到所有的课程（只读出来一门课），应该是semester_info没有读取到所有信息。请问该如何修改呢？

**Comment by GhostFrankWu** [comment]
不确定是因为学期不同还是课程类型不同导致的问题，您可以：
1. 首先登录tis后打开新标签页，开启F12之后访问https://tis.sustech.edu.cn/Xsxk/query/1   
2. 之后查看对queryYxkc（https://tis.sustech.edu.cn/Xsxk/queryYxkc）的请求，一般是XHR类请求最后一条  
3. 最后查看json格式的响应正文中的xkgzszList字段，即为您所在分组的全部课程类型，该字段如下：
```
"xkgzszList": [
        {
            "xkfsdm": "bxxk",
            "xkfsmc": "通识必修选课",
            "xkfsmc_en": "bxxk",
```
目前脚本收录的本科课程类型有：
`course_types = {'bxxk': "通识必修选课", 'xxxk': "通识选修选课", "kzyxk": '培养方案内课程', "zynknjxk": '非培养方案内课程'}`
如果您看到了新的分类类型，可以在这里告知我，谢谢！

**Comment by Tloops** [comment]
#10

**Comment by Tloops** [comment]
@GhostFrankWu 题主提出的问题或许可以通过我新提出的pr解决，研究生选课确实是有一个新的分类~ -> #10
