### ISSUE TITLE
本科生登录错误

### ISSUE THREAD

**Issue by mayuxuan2004** [GhostFrankWu/SUSTech_Tools#9]
您好，本科生登录CAS过程中一直显示登录错误/密码错误
![image](https://user-images.githubusercontent.com/32015055/188056840-4731d833-c8d6-47b9-ba84-356739ad59eb.png)

**Comment by GhostFrankWu** [comment]
请确认您的输入法是英文状态，或者您可以提前将密码存放于剪贴板内，在输入密码时按一下右键即可完成粘贴，之后按回车即可
